const SUPABASE_URL='https://ythnoeyxovapydbmymdo.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_nfSR2tMCFuHCpkOjjNIakw_P85zunsN';
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let mode='login';
const loginTab=document.getElementById('loginTab'),signupTab=document.getElementById('signupTab'),form=document.getElementById('authForm'),submitBtn=document.getElementById('submitBtn'),message=document.getElementById('message'),registrationFields=document.getElementById('registrationFields'),confirmField=document.getElementById('confirmField');
function setMessage(text,ok=false){message.textContent=text;message.className='message show';message.style.background=ok?'#e7f6ec':'#fdecec';message.style.color=ok?'#146b31':'#9b1c1c';}
function setMode(next){mode=next;loginTab.classList.toggle('active',mode==='login');signupTab.classList.toggle('active',mode==='signup');registrationFields.classList.toggle('hidden',mode!=='signup');confirmField.classList.toggle('hidden',mode!=='signup');submitBtn.textContent=mode==='signup'?'CREATE MEMBER ACCOUNT':'LOGIN';document.getElementById('password').autocomplete=mode==='signup'?'new-password':'current-password';message.className='message';}
loginTab.addEventListener('click',()=>setMode('login'));
signupTab.addEventListener('click',()=>setMode('signup'));
async function routeAfterLogin(){const {data:{session},error:sessionError}=await supabaseClient.auth.getSession();if(sessionError)throw sessionError;if(!session){setMessage('Login session was not created. Please try again.');return false}const {data:profile,error:profileError}=await supabaseClient.from('profiles').select('role,status').eq('id',session.user.id).maybeSingle();if(profileError)throw profileError;if(profile?.role==='admin'&&profile?.status==='active'){window.location.replace('admin.html');return true}window.location.replace('member.html');return true;}
form.addEventListener('submit',async e=>{e.preventDefault();if(submitBtn.disabled)return;message.className='message';submitBtn.disabled=true;submitBtn.textContent=mode==='signup'?'CREATING ACCOUNT…':'LOGGING IN…';try{const email=document.getElementById('email').value.trim().toLowerCase(),password=document.getElementById('password').value;if(!email||!password){setMessage('Please enter your email address and password.');return}if(mode==='signup'){const firstName=document.getElementById('firstName').value.trim(),middleName=document.getElementById('middleName').value.trim(),surname=document.getElementById('surname').value.trim(),nationalId=document.getElementById('nin').value.trim(),phone=document.getElementById('phone').value.trim(),confirm=document.getElementById('confirmPassword').value;if(!firstName||!surname||!phone){setMessage('First name, surname and phone number are required.');return}if(!/^\d{11}$/.test(nationalId)){setMessage('Please enter a valid 11-digit NIN.');return}if(password!==confirm){setMessage('Passwords do not match.');return}const fullName=[firstName,middleName,surname].filter(Boolean).join(' ');const {data,error}=await supabaseClient.auth.signUp({email,password,options:{data:{first_name:firstName,middle_name:middleName,surname,national_id:nationalId,phone,full_name:fullName},emailRedirectTo:new URL('member.html',window.location.href).href}});if(error)throw error;if(data?.session){setMessage('Account created. Opening your member portal…',true);await routeAfterLogin();return}setMessage('Registration successful. Check your email if confirmation is required, then return here to log in.',true)}else{const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error;if(!data?.session)throw new Error('Login succeeded but no active session was returned. Please try again.');setMessage('Login successful. Opening your dashboard…',true);await routeAfterLogin()}}catch(error){console.error('Authentication error:',error);setMessage(error?.message||'Authentication failed. Please try again.')}finally{submitBtn.disabled=false;if(mode==='signup')submitBtn.textContent='CREATE MEMBER ACCOUNT';else submitBtn.textContent='LOGIN'}});
supabaseClient.auth.getSession().then(async({data,error})=>{if(error){console.error('Session check failed:',error);return}if(data.session){try{await routeAfterLogin()}catch(error){console.error('Existing-session routing failed:',error);}}});
