(()=>{"use strict";
const URL="https://ythnoeyxovapydbmymdo.supabase.co",KEY="sb_publishable_nfSR2tMCFuHCpkOjjNIakw_P85zunsN",db=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id), money=n=>"₦"+Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2}), esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c])), state={items:[],suppliers:[],moves:[]};
function msg(t,err=false){const e=$("msg");e.textContent=t;e.className="msg show";if(err)e.style.background="#fff0f0",e.style.color="#a63838";else e.style.background="",e.style.color=""}
async function admin(){const {data:{session},error}=await db.auth.getSession();if(error||!session){location.href="auth.html";throw Error("Session expired. Please sign in again.")}const {data:a,error:e}=await db.rpc("is_admin");if(e||!a){location.href="member.html";throw Error("Administrator access required.")}}
async function rpc(action,payload={}){const {data,error}=await db.rpc("admin_inventory_mutate",{p_action:action,p_payload:payload});if(error)throw Error(error.message);return data}
async function load(){try{await admin();const {data,error}=await db.rpc("admin_inventory_data");if(error)throw Error(error.message);state.items=data?.items||[];state.suppliers=data?.suppliers||[];state.moves=data?.movements||[];render();}catch(e){msg(e.message||"Unable to load inventory.",true)}}
function renderStats(){const active=state.items.filter(x=>!x.archived),products=active.filter(x=>x.item_type==="product"),services=active.filter(x=>x.item_type==="service"),units=products.reduce((s,x)=>s+Number(x.stock||0),0),low=products.filter(x=>Number(x.stock)>0&&Number(x.stock)<=Number(x.reorder_level||0)),out=products.filter(x=>Number(x.stock)===0),cv=products.reduce((s,x)=>s+Number(x.stock||0)*Number(x.cost_price||0),0),rv=products.reduce((s,x)=>s+Number(x.stock||0)*Number(x.selling_price||0),0);$("products").textContent=products.length;$("services").textContent=services.length;$("units").textContent=units.toLocaleString();$("low").textContent=low.length;$("out").textContent=out.length;$("costValue").textContent=money(cv);$("retailValue").textContent=money(rv);$("costValueDetail").textContent=money(cv);$("retailValueDetail").textContent=money(rv)}
function supplierName(id){return state.suppliers.find(x=>x.id===id)?.name||"—"}
function renderSelectors(){const cats=[...new Set(state.items.map(x=>x.category).filter(Boolean))].sort(),cat=$("filterCategory"),old=cat.value;cat.innerHTML='<option value="">All categories</option>'+cats.map(x=>'<option>'+esc(x)+'</option>').join("");cat.value=cats.includes(old)?old:"";const ss='<option value="">No supplier</option>'+state.suppliers.filter(x=>x.active).map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join("");$("supplier").innerHTML=ss;$("moveSupplier").innerHTML='<option value="">Supplier (optional)</option>'+state.suppliers.filter(x=>x.active).map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join("");renderMoveItems()}
function renderMoveItems(){const q=($("itemPickerSearch")?.value||"").trim().toLowerCase(),list=state.items.filter(x=>x.item_type==="product"&&!x.archived&&(!q||x.name.toLowerCase().includes(q)||(x.sku||"").toLowerCase().includes(q)));$("moveItem").innerHTML='<option value="">Select product</option>'+list.map(x=>'<option value="'+x.id+'">'+esc(x.name)+" · "+x.stock+" "+esc(x.unit)+'</option>').join("")}
function renderItems(){const q=$("search").value.trim().toLowerCase(),cat=$("filterCategory").value,type=$("filterType").value,status=$("filterStatus").value;let a=state.items.filter(x=>(!q||x.name.toLowerCase().includes(q)||(x.sku||"").toLowerCase().includes(q))&&(!cat||x.category===cat)&&(!type||x.item_type===type));a=a.filter(x=>status==="archived"?x.archived:!x.archived&&(!status||status==="in"?(x.item_type==="service"||Number(x.stock)>Number(x.reorder_level||0)):status==="low"?Number(x.stock)>0&&Number(x.stock)<=Number(x.reorder_level||0):status==="out"?x.item_type==="product"&&Number(x.stock)===0:true));$("itemTable").innerHTML=a.length?a.map(x=>{const st=x.archived?"ARCHIVED":x.item_type==="service"?"SERVICE":Number(x.stock)===0?"OUT OF STOCK":Number(x.stock)<=Number(x.reorder_level||0)?"LOW STOCK":"IN STOCK";const cls=st==="OUT OF STOCK"?"out":st==="LOW STOCK"?"low":"ok";return '<tr><td><strong>'+esc(x.name)+'</strong><br><small>'+esc(x.description||"")+'</small></td><td>'+esc(x.sku||"—")+'</td><td>'+esc(x.category||"—")+'</td><td>'+esc(x.item_type)+'</td><td>'+esc(supplierName(x.supplier_id))+'</td><td>'+money(x.selling_price)+'</td><td>'+money(x.cost_price)+'</td><td>'+Number(x.stock||0).toLocaleString()+" "+esc(x.unit)+'</td><td class="'+cls+'">'+st+'</td><td class="actions">'+(x.archived?'<button class="btn" data-restore="'+x.id+'">RESTORE</button>':'<button class="btn gray" data-edit="'+x.id+'">EDIT</button> <button class="btn red" data-archive="'+x.id+'">ARCHIVE</button>')+'</td></tr>'}).join(""):'<tr><td colspan="10">No matching inventory items.</td></tr>'}
function renderSuppliers(){$("supplierTable").innerHTML=state.suppliers.length?state.suppliers.map(x=>'<tr><td><strong>'+esc(x.name)+'</strong></td><td>'+esc(x.phone||"—")+'</td><td>'+esc(x.email||"—")+'</td><td>'+ (x.active?"ACTIVE":"INACTIVE")+'</td><td><button class="btn gray" data-supplier-edit="'+x.id+'">EDIT</button></td></tr>').join(""):'<tr><td colspan="5">No suppliers.</td></tr>'}
function renderMoves(){const q=$("moveSearch").value.trim().toLowerCase(),type=$("filterMoveType").value,from=$("fromDate").value,to=$("toDate").value;const a=state.moves.filter(m=>{const d=m.created_at.slice(0,10),s=[m.item_name,m.reference,m.counterparty,m.notes].join(" ").toLowerCase();return(!type||m.movement_type===type)&&(!q||s.includes(q))&&(!from||d>=from)&&(!to||d<=to)});$("movementTable").innerHTML=a.length?a.map(m=>'<tr><td>'+new Date(m.created_at).toLocaleString("en-NG")+'</td><td>'+esc(m.item_name)+'<br><small>'+esc(m.sku||"")+'</small></td><td>'+esc(m.movement_type.replaceAll("_"," ").toUpperCase())+'</td><td>'+m.quantity+'</td><td>'+m.previous_stock+'</td><td>'+m.new_stock+'</td><td>'+money(m.total_value)+'</td><td>'+esc(supplierName(m.supplier_id))+(m.counterparty?" / "+esc(m.counterparty):"")+'</td><td>'+esc(m.reference||"—")+'</td><td>'+esc(m.notes||"—")+'</td></tr>').join(""):'<tr><td colspan="10">No matching movements.</td></tr>'}
function renderReports(){const p=state.items.filter(x=>!x.archived&&x.item_type==="product"),low=p.filter(x=>Number(x.stock)>0&&Number(x.stock)<=Number(x.reorder_level||0)),out=p.filter(x=>Number(x.stock)===0),from=$("reportFromDate")?.value||"",to=$("reportToDate")?.value||"";const filteredMoves=state.moves.filter(x=>{const d=(x.created_at||"").slice(0,10);return(!from||d>=from)&&(!to||d<=to)}),purchase=filteredMoves.filter(x=>x.movement_type==="purchase").reduce((s,x)=>s+Number(x.total_value||0),0),sales=filteredMoves.filter(x=>x.movement_type==="sale").reduce((s,x)=>s+Number(x.total_value||0),0),damaged=filteredMoves.filter(x=>x.movement_type==="damaged").reduce((s,x)=>s+Number(x.quantity||0),0),lost=filteredMoves.filter(x=>x.movement_type==="lost").reduce((s,x)=>s+Number(x.quantity||0),0);const alertHtml=(low.concat(out)).map(x=>'<div class="'+(Number(x.stock)===0?"out":"low")+'" style="padding:5px 0">'+esc(x.name)+" — "+(Number(x.stock)===0?"OUT OF STOCK":x.stock+" "+esc(x.unit)+" remaining")+'</div>').join("")||'<div class="ok">No low/out-of-stock alerts.</div>';$("alerts").innerHTML=alertHtml;$("alertsReport").innerHTML=alertHtml;$("summary").innerHTML='<div>Report period: <strong>'+esc(from||"All")+' to '+esc(to||"All")+'</strong></div><div>Active items: <strong>'+state.items.filter(x=>!x.archived).length+'</strong></div><div>Purchase value recorded: <strong>'+money(purchase)+'</strong></div><div>Sales value recorded: <strong>'+money(sales)+'</strong></div><div>Damaged units: <strong>'+damaged.toLocaleString()+'</strong></div><div>Lost units: <strong>'+lost.toLocaleString()+'</strong></div><div>Movements in period: <strong>'+filteredMoves.length+'</strong></div>'}
function render(){renderStats();renderSelectors();renderItems();renderSuppliers();renderMoves();renderReports()}
function resetItem(){ $("itemForm").reset();$("itemId").value="";$("unit").value="piece";$("itemType").value="product";$("saveItem").textContent="ADD ITEM";$("cancelEdit").classList.add("hidden");$("openingStock").disabled=false}
$("itemForm").onsubmit=async e=>{e.preventDefault();const id=$("itemId").value,payload={id,name:$("name").value.trim(),sku:$("sku").value.trim(),category:$("category").value.trim(),unit:$("unit").value.trim(),item_type:$("itemType").value,supplier_id:$("supplier").value,selling_price:+$("sellingPrice").value,cost_price:+$("costPrice").value||0,reorder_level:+$("reorder").value||0,description:$("description").value.trim()};try{if(id){await rpc("update_item",payload)}else{payload.stock=+$("openingStock").value||0;await rpc("create_item",payload)}msg(id?"Item updated.":"Item added to inventory.");resetItem();await load()}catch(x){msg(x.message,true)}};
$("cancelEdit").onclick=resetItem;
$("supplierForm").onsubmit=async e=>{e.preventDefault();const id=$("supplierId").value,p={id,name:$("supplierName").value.trim(),phone:$("supplierPhone").value.trim(),email:$("supplierEmail").value.trim(),address:$("supplierAddress").value.trim(),notes:$("supplierNotes").value.trim(),active:true};try{await rpc(id?"update_supplier":"create_supplier",p);$("supplierForm").reset();$("supplierId").value="";$("cancelSupplier").classList.add("hidden");msg(id?"Supplier updated.":"Supplier added.");await load()}catch(x){msg(x.message,true)}};
$("cancelSupplier").onclick=()=>{$("supplierForm").reset();$("supplierId").value="";$("cancelSupplier").classList.add("hidden")};
$("movementForm").onsubmit=async e=>{e.preventDefault();const p={item_id:$("moveItem").value,movement_type:$("movementType").value,quantity:+$("qty").value,unit_cost:+$("unitCost").value||0,unit_price:+$("unitPrice").value||0,supplier_id:$("moveSupplier").value,counterparty:$("counterparty").value.trim(),reference:$("reference").value.trim(),notes:$("moveNotes").value.trim()};try{const r=await rpc("move_stock",p);msg("Stock movement posted. Reference: "+r.reference);e.target.reset();await load()}catch(x){msg(x.message,true)}};
$("itemPickerSearch")?.addEventListener("input",renderMoveItems);document.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;try{if(b.dataset.movePreset){$("movementType").value=b.dataset.movePreset;$("movementForm").scrollIntoView({behavior:"smooth",block:"start"});$("moveItem").focus();return;}if(b.dataset.edit){const x=state.items.find(i=>i.id===b.dataset.edit);if(!x)return;$("itemId").value=x.id;$("name").value=x.name;$("sku").value=x.sku||"";$("category").value=x.category||"";$("unit").value=x.unit||"piece";$("itemType").value=x.item_type;$("supplier").value=x.supplier_id||"";$("sellingPrice").value=x.selling_price;$("costPrice").value=x.cost_price;$("reorder").value=x.reorder_level;$("description").value=x.description||"";$("openingStock").value=x.stock;$("openingStock").disabled=true;$("saveItem").textContent="SAVE CHANGES";$("cancelEdit").classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})}else if(b.dataset.archive&&confirm("Archive this item?")){await rpc("archive_item",{id:b.dataset.archive});msg("Item archived.");await load()}else if(b.dataset.restore){await rpc("restore_item",{id:b.dataset.restore});msg("Item restored.");await load()}else if(b.dataset.supplierEdit){const x=state.suppliers.find(s=>s.id===b.dataset.supplierEdit);$("supplierId").value=x.id;$("supplierName").value=x.name;$("supplierPhone").value=x.phone||"";$("supplierEmail").value=x.email||"";$("supplierAddress").value=x.address||"";$("supplierNotes").value=x.notes||"";$("cancelSupplier").classList.remove("hidden")}}catch(x){msg(x.message,true)}});
["search","filterCategory","filterType","filterStatus","filterMoveType","moveSearch","fromDate","toDate"].forEach(id=>$(id).addEventListener("input",render));
$("applyReport").onclick=()=>{const from=$("reportFromDate").value,to=$("reportToDate").value,notice=$("reportMsg");if(from&&to&&from>to){notice.textContent="From date cannot be later than To date.";notice.style.color="#a63838";return}notice.textContent="Report applied.";notice.style.color="#126b42";renderReports()};
$("refresh").onclick=load;load();
})();