(()=>{"use strict";
const URL="https://ythnoeyxovapydbmymdo.supabase.co",KEY="sb_publishable_nfSR2tMCFuHCpkOjjNIakw_P85zunsN",db=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id),money=n=>"₦"+Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});
let items=[],rotation=0,drag=null,currentUserId="";
const transferState={mode:"internal",verified:false,banks:[],providers:[]};
const NETWORKS=[{code:"mtn",name:"MTN Nigeria",type:"network"},{code:"airtel",name:"Airtel Nigeria",type:"network"},{code:"glo",name:"Glo Nigeria",type:"network"},{code:"9mobile",name:"9mobile Nigeria",type:"network"}];
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function setTransferStatus(msg,ok=false){const e=$("transferStatus");e.textContent=msg||"";e.className="transferStatus "+(msg?(ok?"ok":"err"):"")}
function fillTransferItems(){const s=$("transferSource"),d=$("transferDestination");if(!s||!d)return;const oldS=s.value,oldD=d.value;const opts=items.map(x=>'<option value="'+x.id+'">'+esc(x.name)+" · "+money(x.amount)+"</option>").join("");s.innerHTML=opts;d.innerHTML='<option value="">Select destination…</option>'+opts;s.value=items.some(x=>x.id===oldS)?oldS:(items[0]?.id||"");d.value=items.some(x=>x.id===oldD)?oldD:""}
function fillProviders(){const q=String($("providerSearch")?.value||"").trim().toLowerCase(),list=[...transferState.banks.map(x=>({...x,type:"bank"})),...NETWORKS],filtered=list.filter(x=>x.name.toLowerCase().includes(q)||String(x.code).toLowerCase().includes(q));$("providerSelect").innerHTML='<option value="">Select bank or network provider…</option>'+filtered.map(x=>'<option value="'+esc(x.code)+'" data-type="'+x.type+'">'+esc(x.name)+(x.type==="network"?" · Network":"")+"</option>").join("");transferState.providers=filtered}
async function loadBanks(){try{const {data:{session}}=await db.auth.getSession();if(!session)return;const r=await fetch(URL+"/functions/v1/wallet-board-transfer",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify({action:"banks"})});const b=await r.json();if(!r.ok)throw Error(b.error||"Unable to load banks.");transferState.banks=b.banks||[];fillProviders()}catch(e){setTransferStatus(e.message||"Unable to load banks.")}}
function recalc(){const a=Math.max(0,Number($("transferAmount")?.value||0)),f=Math.max(0,Number($("serviceFee")?.value||0));$("feeAmount").textContent=money(a);$("feeValue").textContent=money(f);$("totalDebit").textContent=money(a+f)}
function setMode(mode){transferState.mode=mode;document.querySelectorAll(".mode").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));$("internalDestinationWrap").style.display=mode==="internal"?"block":"none";$("thirdPartyFields").style.display=mode==="third_party"?"block":"none";$("transferDestination").required=mode==="internal";transferState.verified=false;$("verifiedName").textContent="";setTransferStatus("");if(mode==="third_party"&&!transferState.banks.length)loadBanks()}
async function verifyAccount(){const opt=$("providerSelect").selectedOptions[0],code=$("providerSelect").value,num=$("accountNumber").value.trim();if(!opt||!code)return alert("Select a bank or network provider.");if(opt.dataset.type!=="bank")return alert("Account-name verification is available for bank accounts. Network providers use a phone number.");if(!/^\d{10}$/.test(num))return alert("Enter the 10-digit bank account number.");const btn=$("verifyAccount");btn.disabled=true;btn.textContent="VERIFYING…";setTransferStatus("");try{const {data:{session}}=await db.auth.getSession();const r=await fetch(URL+"/functions/v1/wallet-board-transfer",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify({action:"resolve",bank_code:code,account_number:num})});const b=await r.json();if(!r.ok)throw Error(b.error||"Account verification failed.");$("verifiedName").textContent="✓ "+(b.account_name||"Account verified");transferState.verified=true}catch(e){transferState.verified=false;setTransferStatus(e.message||"Account verification failed")}finally{btn.disabled=false;btn.textContent="VERIFY ACCOUNT"}}
async function submitTransfer(e){e.preventDefault();const source=$("transferSource").value,amount=Number($("transferAmount").value),fee=Math.max(0,Number($("serviceFee").value||0)),total=amount+fee;if(!source||!Number.isFinite(amount)||amount<=0||!Number.isFinite(fee))return setTransferStatus("Enter a valid amount and service fee.");if(transferState.mode==="internal"){const dest=$("transferDestination").value;if(!dest||dest===source)return setTransferStatus("Choose a different destination wallet item.")}else{const opt=$("providerSelect").selectedOptions[0];if(!opt||!$("providerSelect").value)return setTransferStatus("Select a bank or network provider.");if(opt.dataset.type!=="bank")return setTransferStatus("Network-provider cash transfer is not enabled yet; bank payout is ready.");if(!transferState.verified)return setTransferStatus("Verify the bank account before transferring")}if(!confirm("Transfer "+money(amount)+" and charge service fee "+money(fee)+"? Total debit: "+money(total)))return;const btn=$("transferSubmit");btn.disabled=true;btn.textContent="PROCESSING…";setTransferStatus("");try{if(transferState.mode==="internal"){const {data,error}=await db.rpc("wallet_board_internal_transfer",{p_source_item_id:source,p_destination_item_id:$("transferDestination").value,p_amount:amount,p_service_fee:fee});if(error)throw error;setTransferStatus("Transfer successful · "+data.reference,true)}else{const {data:{session}}=await db.auth.getSession();const r=await fetch(URL+"/functions/v1/wallet-board-transfer",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify({action:"transfer",source_item_id:source,bank_code:$("providerSelect").value,account_number:$("accountNumber").value.trim(),account_name:$("verifiedName").textContent.replace(/^✓ /,""),amount,service_fee:fee})});const b=await r.json();if(!r.ok)throw Error(b.error||"Third-party transfer failed.");setTransferStatus("Transfer submitted · "+(b.transfer?.reference||"reference pending"),true)}await load();fillTransferItems();$("transferAmount").value="";$("serviceFee").value="0";recalc()}catch(err){setTransferStatus(err.message||"Transfer failed")}finally{btn.disabled=false;btn.textContent="TRANSFER"}}
function initTransfer(){fillTransferItems();document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$("providerSearch").addEventListener("input",fillProviders);$("verifyAccount").onclick=verifyAccount;$("transferAmount").addEventListener("input",recalc);$("serviceFee").addEventListener("input",recalc);$("transferForm").onsubmit=submitTransfer;setMode("internal");recalc()}
function iconFor(name){const n=String(name||"").trim();return n.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()||"◉"}
async function admin(){const {data:{session},error}=await db.auth.getSession();if(error||!session){location.href="auth.html";throw Error("Session expired.")}const {data:a,error:e}=await db.rpc("is_admin");if(e||!a){location.href="member.html";throw Error("Administrator access required.")}}
async function load(){const {data:{session},error:sessionError}=await db.auth.getSession();if(sessionError||!session){location.href="auth.html";throw Error("Session expired.")}currentUserId=session.user.id;await admin();const {data,error}=await db.from("inventory_visual_items").select("*").order("sort_order",{ascending:true}).order("created_at",{ascending:true});if(error)throw error;items=data||[];if(!items.length){for(const [i,n] of ["PalmPay","GTB","FCMB"].entries()){const {error:e}=await db.from("inventory_visual_items").insert({name:n,amount:0,icon:iconFor(n),sort_order:i});if(e)throw e}const {data:d,error:e}=await db.from("inventory_visual_items").select("*").order("sort_order",{ascending:true});if(e)throw e;items=d||[]}render()}
function positions(){const n=items.length;if(!n)return[];const rx=Math.min(370,Math.max(170,window.innerWidth*.34)),ry=Math.min(255,Math.max(175,window.innerWidth*.23));return items.map((x,i)=>{const a=(i/n)*Math.PI*2+rotation-Math.PI/2;return {x:rx*Math.cos(a),y:ry*Math.sin(a),z:Math.sin(a)}})}
function render(){const ring=$("ring");ring.innerHTML="";$("empty").style.display=items.length?"none":"grid";let total=items.reduce((a,x)=>a+Number(x.amount||0),0);$("totalAmount").textContent=money(total);$("itemCount").textContent=items.length+" item"+(items.length===1?"":"s");positions().forEach((p,i)=>{const x=items[i],node=document.createElement("div");node.className="node";node.style.transform="translate("+p.x+"px,"+p.y+"px) scale("+(0.88+p.z*.08)+")";node.style.zIndex=String(20+Math.round((p.z+1)*10));node.innerHTML='<div class="ico">'+iconFor(x.name)+'</div><b title="'+x.name.replace(/"/g,"&quot;")+'">'+x.name.replace(/</g,"&lt;")+'</b><small>'+money(x.amount)+'</small>';node.addEventListener("click",()=>editItem(x));ring.appendChild(node)});renderList();fillTransferItems()}
function renderList(){const e=$("existing");e.innerHTML=items.map(x=>'<div class="list-row"><div><b>'+x.name.replace(/</g,"&lt;")+'</b><br><span>'+money(x.amount)+'</span></div><button class="danger" data-id="'+x.id+'">Delete</button></div>').join("");e.querySelectorAll("[data-id]").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this item?"))return;const {error}=await db.from("inventory_visual_items").delete().eq("id",b.dataset.id);if(error)return alert(error.message);items=items.filter(x=>x.id!==b.dataset.id);render()})}
async function editItem(x){const amount=prompt("Latest amount for "+x.name,Number(x.amount||0));if(amount===null)return;const n=Number(amount);if(!Number.isFinite(n)||n<0)return alert("Enter a valid amount.");const {data,error}=await db.from("inventory_visual_items").update({amount:n,updated_at:new Date().toISOString()}).eq("id",x.id).select().single();if(error)return alert(error.message);Object.assign(x,data);render()}
$("addBtn").onclick=()=>{$("modal").classList.add("show");$("itemName").focus()};
$("cancelBtn").onclick=()=>{$("modal").classList.remove("show");$("itemForm").reset();$("adminPin").value=""};
$("modal").addEventListener("click",e=>{if(e.target.id==="modal")$("cancelBtn").click()});
$("itemForm").onsubmit=async e=>{e.preventDefault();const userId=currentUserId,name=$("itemName").value.trim(),amount=Number($("itemAmount").value),pin=$("adminPin").value.trim();if(!userId)return alert("Session expired. Please sign in again.");if(!name||!Number.isFinite(amount)||amount<0)return alert("Enter a valid item name and amount.");if(!/^\\d{6}$/.test(pin))return alert("Enter your 6-digit administrator PIN.");const btn=e.submitter;btn.disabled=true;btn.textContent="ADDING…";try{const {data,error}=await db.rpc("admin_add_inventory_visual_item",{p_user_id:userId,p_name:name,p_amount:amount,p_admin_pin:pin});if(error)throw error;items.push(data);$("cancelBtn").click();render()}catch(err){alert(err.message||"Unable to add item.")}finally{btn.disabled=false;btn.textContent="Add item"}};
$("board").addEventListener("pointerdown",e=>{if(e.target.closest(".node")||e.target.closest("button"))return;drag={x:e.clientX,y:e.clientY,r:rotation};$("board").setPointerCapture(e.pointerId)});
$("board").addEventListener("pointermove",e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;rotation=drag.r+(dx+dy*.35)/160;render()});
$("board").addEventListener("pointerup",e=>{drag=null;try{$("board").releasePointerCapture(e.pointerId)}catch{}});
$("board").addEventListener("pointercancel",()=>drag=null);
initTransfer();load().catch(e=>alert(e.message||"Unable to load wallet board."));
})();