(()=>{"use strict";
const URL="https://ythnoeyxovapydbmymdo.supabase.co",KEY="sb_publishable_nfSR2tMCFuHCpkOjjNIakw_P85zunsN",db=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id),money=n=>"₦"+Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});
let items=[],rotation=0,drag=null,currentUserId="";
function iconFor(name){const n=String(name||"").trim();return n.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()||"◉"}
async function admin(){const {data:{session},error}=await db.auth.getSession();if(error||!session){location.href="auth.html";throw Error("Session expired.")}const {data:a,error:e}=await db.rpc("is_admin");if(e||!a){location.href="member.html";throw Error("Administrator access required.")}}
async function load(){const {data:{session},error:sessionError}=await db.auth.getSession();if(sessionError||!session){location.href="auth.html";throw Error("Session expired.")}currentUserId=session.user.id;await admin();const {data,error}=await db.from("inventory_visual_items").select("*").order("sort_order",{ascending:true}).order("created_at",{ascending:true});if(error)throw error;items=data||[];if(!items.length){for(const [i,n] of ["PalmPay","GTB","FCMB"].entries()){const {error:e}=await db.from("inventory_visual_items").insert({name:n,amount:0,icon:iconFor(n),sort_order:i});if(e)throw e}const {data:d,error:e}=await db.from("inventory_visual_items").select("*").order("sort_order",{ascending:true});if(e)throw e;items=d||[]}render()}
function positions(){const n=items.length;if(!n)return[];const rx=Math.min(370,Math.max(170,window.innerWidth*.34)),ry=Math.min(255,Math.max(175,window.innerWidth*.23));return items.map((x,i)=>{const a=(i/n)*Math.PI*2+rotation-Math.PI/2;return {x:rx*Math.cos(a),y:ry*Math.sin(a),z:Math.sin(a)}})}
function render(){const ring=$("ring");ring.innerHTML="";$("empty").style.display=items.length?"none":"grid";let total=items.reduce((a,x)=>a+Number(x.amount||0),0);$("totalAmount").textContent=money(total);$("itemCount").textContent=items.length+" item"+(items.length===1?"":"s");positions().forEach((p,i)=>{const x=items[i],node=document.createElement("div");node.className="node";node.style.transform="translate("+p.x+"px,"+p.y+"px) scale("+(0.88+p.z*.08)+")";node.style.zIndex=String(20+Math.round((p.z+1)*10));node.innerHTML='<div class="ico">'+iconFor(x.name)+'</div><b title="'+x.name.replace(/"/g,"&quot;")+'">'+x.name.replace(/</g,"&lt;")+'</b><small>'+money(x.amount)+'</small>';node.addEventListener("click",()=>editItem(x));ring.appendChild(node)});renderList()}
function renderList(){const e=$("existing");e.innerHTML=items.map(x=>'<div class="list-row"><div><b>'+x.name.replace(/</g,"&lt;")+'</b><br><span>'+money(x.amount)+'</span></div><button class="danger" data-id="'+x.id+'">Delete</button></div>').join("");e.querySelectorAll("[data-id]").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this item?"))return;const {error}=await db.from("inventory_visual_items").delete().eq("id",b.dataset.id);if(error)return alert(error.message);items=items.filter(x=>x.id!==b.dataset.id);render()})}
async function editItem(x){const amount=prompt("Latest amount for "+x.name,Number(x.amount||0));if(amount===null)return;const n=Number(amount);if(!Number.isFinite(n)||n<0)return alert("Enter a valid amount.");const {data,error}=await db.from("inventory_visual_items").update({amount:n,updated_at:new Date().toISOString()}).eq("id",x.id).select().single();if(error)return alert(error.message);Object.assign(x,data);render()}
$("addBtn").onclick=()=>{$("modal").classList.add("show");$("itemName").focus()};
$("cancelBtn").onclick=()=>{$("modal").classList.remove("show");$("itemForm").reset();$("adminPin").value=""};
$("modal").addEventListener("click",e=>{if(e.target.id==="modal")$("cancelBtn").click()});
$("itemForm").onsubmit=async e=>{e.preventDefault();const userId=currentUserId,name=$("itemName").value.trim(),amount=Number($("itemAmount").value),pin=$("adminPin").value.trim();if(!userId)return alert("Session expired. Please sign in again.");if(!name||!Number.isFinite(amount)||amount<0)return alert("Enter a valid item name and amount.");if(!/^\\d{6}$/.test(pin))return alert("Enter your 6-digit administrator PIN.");const btn=e.submitter;btn.disabled=true;btn.textContent="ADDING…";try{const {data,error}=await db.rpc("admin_add_inventory_visual_item",{p_user_id:userId,p_name:name,p_amount:amount,p_admin_pin:pin});if(error)throw error;items.push(data);$("cancelBtn").click();render()}catch(err){alert(err.message||"Unable to add item.")}finally{btn.disabled=false;btn.textContent="Add item"}};
$("board").addEventListener("pointerdown",e=>{if(e.target.closest(".node")||e.target.closest("button"))return;drag={x:e.clientX,y:e.clientY,r:rotation};$("board").setPointerCapture(e.pointerId)});
$("board").addEventListener("pointermove",e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;rotation=drag.r+(dx+dy*.35)/160;render()});
$("board").addEventListener("pointerup",e=>{drag=null;try{$("board").releasePointerCapture(e.pointerId)}catch{}});
$("board").addEventListener("pointercancel",()=>drag=null);
load().catch(e=>alert(e.message||"Unable to load wallet board."));
})();