const SUPABASE_URL="https://ythnoeyxovapydbmymdo.supabase.co",SUPABASE_PUBLISHABLE_KEY="sb_publishable_nfSR2tMCFuHCpkOjjNIakw_P85zunsN",supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY),$=id=>document.getElementById(id),p=new URLSearchParams(location.search),action=p.get("action")||"send",effectiveAction=action==="request-loan"?"request-qard":action==="transfer"?"send":action;

const configs={
 send:["Inter-Wallet Transfer","Transfer funds securely to another active Habsco Cooperative member."],
 fund:["Add Money","Submit a wallet funding payment for verification."],save:["Save in Cooperative","Move money into a cooperative account."],
 qard:["Interest-Free Loan","Submit an interest-free loan request for cooperative review."],"request-qard":["Request Interest-Free Loan","Submit an interest-free loan request for cooperative review."],"repay-qard":["Repay Interest-Free Loan","Submit repayment details for a disbursed loan."],
 receive:["Receive Fund","Approved funding and member transfers are credited server-side."],
 airtime:["Airtime","Select the provider, enter the receiver and amount, then complete the provider-validated purchase."],
 data:["Mobile Data","Select the provider and live package, enter the receiver, then complete the provider-validated purchase."],
 tv:["TV Subscription","Select the provider and live package, verify the subscriber, then complete the provider-validated purchase."],
 education:["Education","Select the provider and live package, enter the candidate details, then complete the provider-validated purchase."],
 electricity:["Electricity","Select the distribution company, verify the meter customer name, then pay."]
};
const [title,subtitle]=configs[action]||configs[effectiveAction]||configs.send;
function msg(t,ok=true){const e=$("msg");e.textContent=t;e.style.background=ok?"#eef8f2":"#fff1f1";e.style.color=ok?"#087443":"#a52a2a";e.classList.add("show")}
function form(html,submitText="CONTINUE"){$("formArea").innerHTML='<form id="actionForm" class="form">'+html+'<button id="actionSubmit" class="btn" type="submit">'+submitText+'</button></form>'}
async function auth(){let {data:{session},error}=await supabaseClient.auth.getSession();if(error||!session){const r=await supabaseClient.auth.refreshSession();if(r.error||!r.data.session){location.href="auth.html";return null}session=r.data.session}return session}
async function callProvider(body){await auth();const {data,error}=await supabaseClient.functions.invoke("utility-vps-proxy",{body});if(error){let d="";try{d=error.context?JSON.stringify(await error.context.json()):""}catch{}throw new Error(d||error.message||"Utility service request failed.")}if(data?.error)throw new Error(data.error.message||data.error);return data||{}}
function esc(v){return String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function rowsOf(r){const x=r?.data?.data??r?.data??r?.providers??r;return Array.isArray(x)?x:[]}
function packageCode(x){return String(x?.code??x?.variation_code??x?.variationCode??x?.package_code??x?.id??"").trim()}
function packageName(x){return String(x?.package??x?.name??x?.package_name??x?.variation??x?.description??packageCode(x)).trim()}
function packageAmount(x){const n=Number(x?.amount??x?.price??x?.selling_price??x?.sellingPrice);return Number.isFinite(n)?n:null}
async function loadProviderSelect(id,providerAction,empty){const s=$(id);s.disabled=true;s.innerHTML='<option value="">Loading providers...</option>';try{const r=await callProvider({action:providerAction});const rows=rowsOf(r);if(!rows.length)throw Error("No providers are currently available.");s.innerHTML='<option value="">'+empty+'</option>';const seen=new Set();rows.forEach(x=>{const code=String(x?.short_name??x?.code??x?.provider??x?.name??"").trim();const name=String(x?.name??x?.provider_name??x?.short_name??x?.disco??x?.code??code).trim();if(!code||seen.has(code.toUpperCase()))return;seen.add(code.toUpperCase());const o=document.createElement("option");o.value=code;o.textContent=name===code?name:name+" ("+code+")";s.appendChild(o)});s.disabled=false}catch(e){s.innerHTML='<option value="">Unable to load providers</option>';throw e}}
async function loadPackages(providerAction,provider,selectId){const s=$(selectId);s.disabled=true;s.innerHTML='<option value="">Loading packages...</option>';try{const r=await callProvider({action:providerAction,provider,page:1,limit:100});const rows=rowsOf(r);if(!rows.length){s.innerHTML='<option value="">No packages available</option>';return}const seen=new Set();s.innerHTML='<option value="">Select package</option>';rows.forEach(x=>{const code=packageCode(x);if(!code||seen.has(code))return;seen.add(code);const o=document.createElement("option");o.value=code;const n=packageName(x),a=packageAmount(x);o.textContent=a!=null?n+" — ₦"+a.toLocaleString("en-NG"):n;s.appendChild(o)});s.disabled=false}catch(e){s.innerHTML='<option value="">Unable to load packages</option>';throw e}}
function pinField(){return '<label>Transaction PIN<input id="transactionPin" type="password" inputmode="numeric" maxlength="6" pattern="[0-9]{6}" placeholder="6-digit PIN" autocomplete="off" required></label>'}
async function setupUtility(){
 if(effectiveAction==="airtime"){
  form('<label>Provider<select id="provider" required><option value="">Loading providers...</option></select></label><label>Receiver phone number<input id="receiver" inputmode="tel" maxlength="16" placeholder="08012345678" required></label><label>Amount (NGN)<input id="amount" type="number" min="1" step="1" required></label>'+pinField());
  try{await loadProviderSelect("provider","airtime-providers","Select provider")}catch(e){msg(e.message,false)}
 }
 if(effectiveAction==="data"||effectiveAction==="tv"||effectiveAction==="education"){
  const a=effectiveAction, label=a==="tv"?"TV Provider":a==="education"?"Education Provider":"Mobile Network";
  const receiver=a==="tv"?"Smart Card / Account Number":a==="education"?"Candidate / Receiver Number":"Receiver phone number";
  const input=a==="tv"?"<input id=\"receiver\" inputmode=\"numeric\" maxlength=\"40\" placeholder=\"Enter smart card or account number\" required>":a==="education"?"<input id=\"receiver\" maxlength=\"40\" placeholder=\"Enter candidate or receiver number\" required>":"<input id=\"receiver\" inputmode=\"tel\" maxlength=\"16\" placeholder=\"08012345678\" required>";
  const extra=a==="tv"?"<label>Phone number (optional)<input id=\"phone\" inputmode=\"tel\" maxlength=\"16\" placeholder=\"08012345678\"></label><label>Email (optional)<input id=\"email\" type=\"email\" maxlength=\"120\"></label>":a==="education"?"<label>Notification phone (optional)<input id=\"phone\" inputmode=\"tel\" maxlength=\"16\" placeholder=\"08012345678\"></label><label>Email (optional)<input id=\"email\" type=\"email\" maxlength=\"120\"></label>":"";
  form('<label>'+label+'<select id="provider" required><option value="">Loading providers...</option></select></label><label>Package<select id="package" required disabled><option value="">Select a provider first</option></select></label><label>'+receiver+input+'</label>'+extra+pinField());
  try{await loadProviderSelect("provider",a+"-providers","Select provider");$("provider").addEventListener("change",async()=>{if($("provider").value){try{await loadPackages(a+"-packages",$("provider").value,"package")}catch(e){msg(e.message,false)}}else{$("package").innerHTML='<option value="">Select a provider first</option>';$("package").disabled=true}})}catch(e){msg(e.message,false)}
 }
 if(effectiveAction==="electricity"){
  form('<label>DisCo<select id="disco" required><option value="">Loading distribution companies...</option></select></label><label>Meter number<input id="meter_number" inputmode="numeric" maxlength="30" required></label><label>Meter type<select id="meter_type"><option value="PREPAID">Prepaid</option><option value="POSTPAID">Postpaid</option></select></label><label>Amount (NGN)<input id="amount" type="number" min="100" step="1" required></label><button id="verifyMeter" class="btn" type="button">VERIFY METER</button><div id="meterResult" class="api-note">Enter the meter details and verify the customer name before payment.</div>'+pinField()+'<div class="api-note">Payment is locked until successful meter verification.</div>');
  let verifiedKey="";const disco=$("disco"),verify=$("verifyMeter"),result=$("meterResult"),submit=$("actionSubmit");submit.disabled=true;
  try{await loadProviderSelect("disco","power-providers","Select distribution company")}catch(e){result.textContent=e.message;result.style.color="#a52a2a"}
  const invalidate=()=>{verifiedKey="";submit.disabled=true;result.textContent="Meter not verified. Verify again before payment.";result.style.color="#a52a2a"};
  ["input","change"].forEach(ev=>{disco.addEventListener(ev,invalidate);$("meter_number").addEventListener(ev,invalidate);$("meter_type").addEventListener(ev,invalidate);$("amount").addEventListener(ev,invalidate)});
  verify.onclick=async()=>{const provider=disco.value.trim(),receiver=$("meter_number").value.trim(),meter_type=$("meter_type").value,amount=Number($("amount").value);if(!provider||!receiver||!Number.isFinite(amount)||amount<=0){result.textContent="Select a DisCo and enter a valid meter number and amount.";result.style.color="#a52a2a";return}verify.disabled=true;verify.textContent="VERIFYING...";try{const r=await callProvider({action:"power-validate",provider,receiver,meter_number:receiver,meter_type,amount});const ci=r?.data?.customer_info||r?.customer_info||{};const name=String(r?.data?.customer_name||r?.customer_name||ci?.customer_name||ci?.customerName||ci?.full_name||"").trim();if(!name)throw Error("Meter verification did not return a customer name. Payment has been blocked.");verifiedKey=[provider,receiver,meter_type,String(amount)].join("|");result.innerHTML="<strong>Verified customer:</strong> "+esc(name);result.style.color="#087443";submit.disabled=false}catch(e){invalidate();result.textContent=e.message||"Meter verification failed."}finally{verify.disabled=false;verify.textContent="VERIFY METER"}};
  submit.getVerifiedKey=()=>verifiedKey;
 }
}
async function init(){
 const session=await auth();if(!session)return;
 if($("title"))$("title").textContent=title;if($("subtitle"))$("subtitle").textContent=subtitle;
 if(["airtime","data","tv","education","electricity"].includes(effectiveAction)){await setupUtility();return}
 if(effectiveAction==="receive"){$("formArea").innerHTML='<div class="api-note">Receive Fund does not create a fake balance. Funds are credited only by approved server-side/admin transactions or completed member transfers.</div>';return}
 if(effectiveAction==="send"){const {data:fc,error:fe}=await supabaseClient.rpc("member_get_feature_controls");const f=Array.isArray(fc)?fc[0]:fc;if(fe)throw fe;if(f?.transfers_enabled===false){$("formArea").innerHTML='<div class="api-note" style="color:#a52a2a;background:#fff1f1;border:1px solid #f0caca;padding:14px;border-radius:12px"><strong>Inter-Wallet Transfer Restricted</strong><br>Inter-Wallet Transfer has been restricted by the administrator. You cannot send money while this restriction is active.</div>';return}form('<label>Member ID<input id="recipient" placeholder="HF-001" required></label><label>Amount (NGN)<input id="amount" type="number" min="1" step="0.01" required></label><label>Note<input id="note" placeholder="Optional note"></label>'+pinField());}
 else if(effectiveAction==="fund")form('<label>Amount (NGN)<input id="amount" type="number" min="1" required></label><label>Payment date<input id="date" type="date" required></label><label>Payment reference<input id="ref" required></label><label>Note<textarea id="note"></textarea></label>');
 else if(effectiveAction==="dividend"){form('<div id="dividendHint" class="api-note">Checking available dividend balance…</div><label>Dividend amount (NGN)<input id="amount" type="number" min="1" step="0.01" required></label>'+pinField(), "WITHDRAW DIVIDEND");try{const {data,error}=await supabaseClient.rpc("member_dashboard_balances");if(error)throw error;const x=Array.isArray(data)?data[0]:data,a=Number(x?.dividend||0),hint=$("dividendHint");if(hint){hint.textContent="Available dividend balance: ₦"+a.toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2})+" — enter any amount up to this balance.";hint.style.color=a>0?"#087443":"#a52a2a"}const input=$("amount");if(input){input.max=a.toFixed(2);input.placeholder=a>0?"Up to ₦"+a.toLocaleString("en-NG",{maximumFractionDigits:2}):"No dividend available"}}catch(e){const hint=$("dividendHint");if(hint)hint.textContent="Unable to load dividend balance. Please try again.";}}
 else if(effectiveAction==="save")form('<label>Account<select id="account"><option value="savings">Savings Account</option><option value="shares">Shares Account</option><option value="special_savings">Special Savings</option></select></label><label>Amount (NGN)<input id="amount" type="number" min="1" step="0.01" required></label><label>Note<input id="note"></label>'+pinField());
 else if(effectiveAction==="qard"||effectiveAction==="request-qard")form('<label>Amount needed (NGN)<input id="amount" type="number" min="1" required></label><label>Repayment plan<select id="plan"><option>₦5,000 monthly for 6 months</option><option>₦10,000 monthly for 3 months</option><option>Discuss with review team</option></select></label><label>Purpose<textarea id="purpose" required></textarea></label>');
 else if(effectiveAction==="repay-qard"){form('<label>Loan request<select id="qard" required><option value="">Loading disbursed loan...</option></select></label><label>Amount (NGN)<input id="amount" type="number" min="1" required></label><label>Payment date<input id="date" type="date" required></label><label>Payment reference<input id="ref" required></label><label>Note<textarea id="note"></textarea></label>');const {data,error}=await supabaseClient.from("qard_requests").select("id,amount,created_at,status").eq("user_id",session.user.id).eq("status","disbursed").order("created_at",{ascending:false});if(!error)$("qard").innerHTML='<option value="">Select disbursed loan</option>'+(data||[]).map(r=>'<option value="'+esc(r.id)+'">₦'+Number(r.amount).toLocaleString()+" · "+new Date(r.created_at).toLocaleDateString("en-NG")+"</option>").join("")}
}
$("formArea").addEventListener("submit",async e=>{if(e.target.id!=="actionForm")return;e.preventDefault();const b=$("actionSubmit");b.disabled=true;try{const bio=window.__hfBioAuthorizationToken||null;let r;
 if(effectiveAction==="send")r=await supabaseClient.rpc("member_transfer",{p_recipient_member_id:$("recipient").value.trim().toUpperCase(),p_amount:Number($("amount").value),p_description:$("note").value.trim()||null,p_transaction_pin:$("transactionPin").value.trim()});
 else if(effectiveAction==="fund")r=await supabaseClient.rpc("member_submit_funding_request",{p_amount:Number($("amount").value),p_paid_at:$("date").value,p_payment_reference:$("ref").value.trim(),p_purpose:"wallet",p_note:$("note").value.trim()||null});
 else if(effectiveAction==="dividend")r=await supabaseClient.rpc("member_withdraw_dividend",{p_amount:Number($("amount").value),p_transaction_pin:$("transactionPin").value.trim()});
 else if(effectiveAction==="save")r=await supabaseClient.rpc("member_contribute_to_account",{p_account_type:$("account").value,p_amount:Number($("amount").value),p_description:$("note").value.trim()||null,p_transaction_pin:$("transactionPin").value.trim()});
 else if(effectiveAction==="qard"||effectiveAction==="request-qard")r=await supabaseClient.rpc("member_submit_qard_request",{p_amount:Number($("amount").value),p_repayment_plan:$("plan").value,purpose:$("purpose").value.trim()});
 else if(effectiveAction==="repay-qard")r=await supabaseClient.rpc("member_submit_qard_repayment",{p_qard_request_id:$("qard").value,p_amount:Number($("amount").value),p_paid_date:$("date").value,p_payment_reference:$("ref").value.trim(),p_note:$("note").value.trim()});
 else if(["airtime","data","tv","education"].includes(effectiveAction)){const base={action:effectiveAction,provider:$("provider").value,receiver:$("receiver").value.trim(),transaction_pin:$("transactionPin").value.trim()};if(effectiveAction==="airtime")base.amount=Number($("amount").value);if(effectiveAction==="data"){base.code=$("package").value}if(effectiveAction==="tv"){base.package=$("package").value;base.phone=$("phone")?.value.trim()||"";base.email=$("email")?.value.trim()||""}if(effectiveAction==="education"){base.code=$("package").value;base.phone_number=$("phone")?.value.trim()||"";base.email=$("email")?.value.trim()||""}r={data:await callProvider(base)}}
 else if(effectiveAction==="electricity"){const key=[$("disco").value.trim(),$("meter_number").value.trim(),$("meter_type").value,String(Number($("amount").value))].join("|");if(!submit.getVerifiedKey||submit.getVerifiedKey()!==key)throw Error("Please verify the meter and customer name before payment.");r={data:await callProvider({action:"electricity",provider:$("disco").value.trim(),receiver:$("meter_number").value.trim(),meter_number:$("meter_number").value.trim(),meter_type:$("meter_type").value,amount:Number($("amount").value),transaction_pin:$("transactionPin").value.trim()})}}
 if(r?.error)throw Error(r.error.message||r.error);msg(effectiveAction==="dividend"?"Dividend withdrawn to Available to Spend. Reference: "+String(r?.data||"" ):(r?.data?.pending?"Transaction submitted and is pending provider confirmation.":"Request submitted successfully."),true);e.target.reset()
 }catch(err){msg(err.message||"Unable to complete this action.",false)}finally{b.disabled=false}});
init().catch(e=>msg(e.message||"Unable to load this form.",false));