(()=>{"use strict";
const URL="https://ythnoeyxovapydbmymdo.supabase.co",KEY="sb_publishable_nfSR2tMCFuHCpkOjjNIakw_P85zunsN";
const db=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const money=n=>"₦"+Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2}),esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c])),lagos=d=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Lagos"}).format(new Date(d));
function range(k){const p=lagos(new Date()).split("-").map(Number),y=p[0],m=p[1],d=p[2],pad=n=>String(n).padStart(2,"0");if(k==="daily")return [y+"-"+pad(m)+"-"+pad(d),new Date(Date.UTC(y,m-1,d+1)).toISOString().slice(0,10)];if(k==="monthly")return [y+"-"+pad(m)+"-01",new Date(Date.UTC(y,m,1)).toISOString().slice(0,10)];if(k==="yearly")return [y+"-01-01",(y+1)+"-01-01"];const x=new Date(Date.UTC(y,m-1,d)),w=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()-w+1);const a=x.toISOString().slice(0,10);x.setUTCDate(x.getUTCDate()+7);return [a,x.toISOString().slice(0,10)]}
async function init(){
 const kind=new URLSearchParams(location.search).get("report");if(!["daily","weekly","monthly","yearly"].includes(kind))return;
 const {data:{user}}=await db.auth.getUser();if(!user){location.href="auth.html";return}
 const [from,to]=range(kind),r=await db.from("pos_sales").select("*").gte("when_at",from+"T00:00:00+00:00").lt("when_at",to+"T00:00:00+00:00").order("when_at",{ascending:false}).limit(2000);
 if(r.error)return alert(r.error.message);const sales=r.data||[],sum=k=>sales.reduce((a,x)=>a+Number(x[k]||0),0),title={daily:"Daily Sales",weekly:"Weekly Sales",monthly:"Monthly Sales",yearly:"Yearly Sales"}[kind],groups={};
 sales.forEach(x=>{const z=groups[x.item||"Other"]||{qty:0,sales:0,cost:0,net:0};z.qty+=Number(x.qty||0);z.sales+=Number(x.sales||0);z.cost+=Number(x.cost||0);z.net+=Number(x.net||0);groups[x.item||"Other"]=z});
 const itemRows=Object.entries(groups).sort((a,b)=>b[1].sales-a[1].sales).map(x=>"<tr><td>"+esc(x[0])+"</td><td>"+x[1].qty+"</td><td>"+money(x[1].sales)+"</td><td>"+money(x[1].cost)+"</td><td>"+money(x[1].net)+"</td></tr>").join("");
 const rows=sales.map(x=>"<tr><td>"+new Date(x.when_at).toLocaleString("en-NG")+"</td><td>"+esc(x.item)+"</td><td>"+esc(x.customer_name||"Walk-in")+"</td><td>"+x.qty+"</td><td>"+money(x.sales)+"</td><td>"+money(x.cost)+"</td><td>"+money(x.gross)+"</td><td>"+money(x.fee)+"</td><td>"+money(x.expense)+"</td><td class='"+(Number(x.net)<0?"loss":"profit")+"'>"+money(x.net)+"</td><td>"+esc(x.method||"—")+"</td><td>"+esc(x.receipt_no||x.receipt||"—")+"</td></tr>").join("");
 const panel=document.createElement("section");panel.className="daily show";panel.id="periodReport";
 panel.innerHTML="<div class='panel'><div class='panel-head'><div><h2>📊 "+title+"</h2><div class='sub'>"+from+" to "+to+" · Live Supabase POS records</div></div><a class='back' href='pos.html'>← POS</a></div><div class='summary'><div class='stat'><small>Sales</small><strong>"+money(sum("sales"))+"</strong></div><div class='stat'><small>Cost</small><strong>"+money(sum("cost"))+"</strong></div><div class='stat'><small>Gross Profit</small><strong>"+money(sum("gross"))+"</strong></div><div class='stat'><small>Fees + Expenses</small><strong>"+money(sum("fee")+sum("expense"))+"</strong></div><div class='stat'><small>Net Profit</small><strong>"+money(sum("net"))+"</strong></div><div class='stat'><small>Transactions</small><strong>"+sales.length+"</strong></div></div></div><div class='panel'><div class='panel-head'><div><h2>Product / Service Performance</h2><div class='sub'>Grouped for this period.</div></div></div><div class='table-wrap'><table class='table'><thead><tr><th>Item</th><th>Qty</th><th>Sales</th><th>Cost</th><th>Net</th></tr></thead><tbody>"+(itemRows||"<tr><td colspan='5' class='empty'>No sales in this period.</td></tr>")+"</tbody></table></div></div><div class='panel'><div class='panel-head'><div><h2>Transaction Register</h2><div class='sub'>All transactions in the selected period.</div></div></div><div class='table-wrap'><table class='table'><thead><tr><th>Date</th><th>Item</th><th>Customer</th><th>Qty</th><th>Sales</th><th>Cost</th><th>Gross</th><th>Fees</th><th>Expenses</th><th>Net</th><th>Payment</th><th>Receipt</th></tr></thead><tbody>"+(rows||"<tr><td colspan='12' class='empty'>No transactions in this period.</td></tr>")+"</tbody></table></div></div>";
 document.querySelector(".wrap").appendChild(panel);
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();