const CACHE='habsco-webapp-v2';
const SHELL=['./','index.html','about.html','programs.html','finance.html','impact.html','gallery.html','contact.html','style.css','app.css','main.js','manifest.json','favicon.svg','logo.svg'];
const FOOTER=`<style>
.site-master-footer{margin-top:52px;background:linear-gradient(145deg,#052f18,#083f20 58%,#0d5b2b);color:#e8f4eb;border-top:1px solid rgba(255,255,255,.12);box-shadow:0 -14px 35px rgba(5,47,24,.12)}
.site-master-footer .footer{max-width:1280px;margin:auto;padding:48px 24px 28px;display:grid;grid-template-columns:1.35fr .8fr 1fr 1.15fr;gap:34px;align-items:start}
.site-master-footer .footer-brand img{display:block;width:170px;max-width:100%;height:auto;max-height:78px;object-fit:contain;object-position:left center;margin:0 0 18px;filter:drop-shadow(0 8px 16px rgba(0,0,0,.20))}
.site-master-footer h4{color:#fff;font-size:13px;letter-spacing:.7px;text-transform:uppercase;margin:4px 0 15px}
.site-master-footer a{color:#dcebe0;text-decoration:none}.site-master-footer .footer>div:not(.footer-brand) a{display:block;margin:0 0 10px;font-size:13px;line-height:1.45}.site-master-footer a:hover{color:#f4c94f}.site-master-footer p{color:#bfd2c4;font-size:13px;line-height:1.65;margin:0 0 12px}
.site-master-footer .social-buttons{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.site-master-footer .social-btn{display:inline-flex!important;align-items:center!important;width:auto!important;margin:0!important;padding:7px 10px;border:1px solid rgba(255,255,255,.16);border-radius:999px;background:rgba(255,255,255,.06);font-size:11px!important;line-height:1!important}.site-master-footer .copyright{max-width:1280px;margin:auto;padding:17px 24px 22px;border-top:1px solid rgba(255,255,255,.12);color:#a9c0ae;font-size:11px;text-align:center}
@media(max-width:1050px){.site-master-footer .footer{grid-template-columns:1.2fr 1fr 1fr;gap:28px}.site-master-footer .footer-brand{grid-column:1/-1}}
@media(max-width:720px){.site-master-footer{margin-top:40px}.site-master-footer .footer{grid-template-columns:1fr 1fr;padding:38px 20px 24px;gap:28px 20px}.site-master-footer .footer-brand{grid-column:1/-1}.site-master-footer .footer-brand img{width:155px;margin-bottom:14px}.site-master-footer .copyright{padding:15px 18px 20px}}
@media(max-width:430px){.site-master-footer .footer{grid-template-columns:1fr}.site-master-footer .footer-brand{grid-column:auto}.site-master-footer .footer-brand img{width:145px}.site-master-footer .social-buttons{max-width:290px}}
</style>
<footer class="site-master-footer"><div class="footer"><div class="footer-brand"><img src="logo.svg" alt="Habsco Sadaqah Jariyah Development Trust"><h3>Habsco Sadaqah Jariyah Development Trust</h3><p>Building a Legacy of Continuous Charity through sustainable projects that benefit communities and generations.</p></div><div><h4>Quick Links</h4><a href="index.html">Home</a><a href="about.html">About Us</a><a href="programs.html">Programs</a></div><div><h4>Programs</h4><a href="programs.html">Waqf &amp; Sustainable Income</a><a href="programs.html">Qard Hasan</a><a href="programs.html">Solar-Powered Clean Water</a><a href="programs.html">Vocational &amp; Digital Skills</a></div><div><h4>Contact Us</h4><p>info@habscosadaqah.org<br>08135684330<br>Kwara State, Nigeria</p><div class="social-buttons"><a class="social-btn" href="https://www.facebook.com/habscosadaqah" target="_blank" rel="noopener">Facebook</a><a class="social-btn" href="https://www.instagram.com/habscosadaqah" target="_blank" rel="noopener">Instagram</a><a class="social-btn" href="https://wa.me/2348135684330" target="_blank" rel="noopener">WhatsApp</a><a class="social-btn" href="https://www.youtube.com/@habscosadaqah" target="_blank" rel="noopener">YouTube</a><a class="social-btn" href="https://www.tiktok.com/@habscosadaqah" target="_blank" rel="noopener">TikTok</a></div></div></div><div class="copyright">© 2026 Habsco Sadaqah Jariyah Development Trust. All Rights Reserved.</div></footer>`;
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
function transform(response){return response.text().then(html=>{if(!/<html/i.test(html)||!/text\/html/i.test(response.headers.get('content-type')||''))return response;html=html.replace(/<footer[\s\S]*?<\/footer>/i,FOOTER);if(!/<footer/i.test(html))html=html.replace(/<\/body>/i,FOOTER+'</body>');return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});});}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const dest=event.request.destination;if(dest==='document')event.respondWith(caches.match(event.request).then(cached=>cached?transform(cached):fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return transform(response)}).catch(()=>caches.match('index.html').then(transform))));else event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return response}).catch(()=>caches.match('index.html'))));});